<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Datepicker_nextMonth</name>
   <tag></tag>
   <elementGuidId>7b0e9244-68f7-4ff1-9da9-9138b2392305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[text()='chevron_right']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
